import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import {readFileSync} from 'node:fs';
const source=readFileSync(new URL('./club-pop-worker.mjs',import.meta.url),'utf8')+'\nexport {currentStudentJob,currentStudentsView};';
const {currentStudentJob:job,currentStudentsView:view}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const db=new DatabaseSync(':memory:');db.exec('PRAGMA foreign_keys=ON; CREATE TABLE members(evo_member_id INTEGER); INSERT INTO members VALUES(1),(3); CREATE TABLE evo_member_cache(payload TEXT); INSERT INTO evo_member_cache VALUES(\'historical\');');db.exec(readFileSync(new URL('./evo-current-schema.sql',import.meta.url),'utf8'));
const wrap=(sql,args=[])=>({bind(...v){return wrap(sql,v)},async first(){return db.prepare(sql).get(...args)},async all(){return {results:db.prepare(sql).all(...args)}},async run(){return db.prepare(sql).run(...args)}});
const env={DB:{prepare:wrap,async batch(ss){db.exec('BEGIN');try{const r=[];for(const s of ss)r.push(await s.run());db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}}};
const s=(id,extra={})=>({id:String(id),name:'Fixture '+id,status:'Active',gympass:false,totalpass:false,fitcoins:90,...extra});
let r=await job(env,{unit:'gym',action:'begin'});assert.equal(r.status,423);
r=await job(env,{unit:'bike',action:'begin'});const id=r.runId;
assert.equal((await job(env,{unit:'bike',action:'begin'})).status,409);
let page=Array.from({length:25},(_,i)=>s(i+1));
r=await job(env,{unit:'bike',action:'ingest',runId:id,skip:0,reportIds:['1'],students:page});assert.equal(r.done,false);assert.equal((await view(env)).counts.total,0);
assert.equal((await job(env,{unit:'bike',action:'ingest',runId:id,skip:25,students:[s(1)]})).status,409);
r=await job(env,{unit:'bike',action:'ingest',runId:id,skip:25,students:[s(26,{gympass:true,totalpass:true,status:'Suspended'})]});assert.equal(r.done,true);
let v=await view(env);assert.equal(v.counts.total,26);assert.equal(v.counts.active,1);assert.equal(v.counts.aggregators,1);assert.equal(v.counts.suspended,1);assert.equal(v.counts.vip,null);assert.equal(v.comparison.both,2);assert.equal(v.lastRequests,3);
r=await job(env,{unit:'bike',action:'begin'});const second=r.runId;
await job(env,{unit:'bike',action:'fail',runId:second,error:'EVO_HTTP_500'});assert.equal((await view(env)).counts.total,26);
r=await job(env,{unit:'bike',action:'begin'});await job(env,{unit:'bike',action:'ingest',runId:r.runId,skip:0,reportIds:['1'],students:[s(1)]});v=await view(env);assert.equal(v.counts.total,1);assert.equal(db.prepare('SELECT COUNT(*) n FROM evo_students').get().n,26);assert.equal(db.prepare('SELECT payload FROM evo_member_cache').get().payload,'historical');assert.equal(v.comparison.onlyClub,1);
assert.equal(db.prepare('PRAGMA foreign_key_check').all().length,0);
console.log('PASS: Gym blocked, one run, partial/failure preserves mirror, duplicates rejected, categories overlap, comparison IDs, removal keeps history, caches untouched, FK integrity.');
