import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import crypto from 'node:crypto';
import fs from 'node:fs';
import vm from 'node:vm';
import worker,{claimEvoMissionVoucher,evoVoucherCode} from './club-pop-worker.mjs';
function fixture(){const db=new DatabaseSync(':memory:');db.exec(`
CREATE TABLE club_voucher_models(id INTEGER PRIMARY KEY,unit TEXT,name TEXT,discount_type INTEGER,discount_value REAL,validity_days INTEGER,contract_ids_json TEXT,enabled INTEGER);
CREATE TABLE club_voucher_requests(id INTEGER PRIMARY KEY AUTOINCREMENT,unit TEXT,model_id INTEGER,member_id INTEGER,source_type TEXT,source_id TEXT,idempotency_key TEXT UNIQUE,delivery_mode TEXT,status TEXT,attempts INTEGER DEFAULT 0,evo_voucher_id INTEGER,assigned_code TEXT,error TEXT,created_at TEXT DEFAULT CURRENT_TIMESTAMP,processed_at TEXT);
CREATE TABLE redemptions(id INTEGER PRIMARY KEY AUTOINCREMENT,member_id INTEGER,redemption_type TEXT,reference_id TEXT,status TEXT,source_type TEXT,source_id TEXT,title TEXT,details TEXT,unit TEXT,dedupe_key TEXT,requested_at TEXT DEFAULT CURRENT_TIMESTAMP,completed_at TEXT);
CREATE TABLE vouchers(id INTEGER PRIMARY KEY AUTOINCREMENT,member_id INTEGER,code TEXT UNIQUE,type TEXT,description TEXT,status TEXT,redemption_id INTEGER,source_type TEXT,source_id TEXT,title TEXT,metadata_json TEXT);
CREATE TABLE evo_request_log(id INTEGER PRIMARY KEY AUTOINCREMENT,unit TEXT,purpose TEXT,method TEXT,endpoint TEXT,status INTEGER,ok INTEGER);
CREATE TABLE evo_unit_config(unit TEXT,dns TEXT,token TEXT,expires_at TEXT,enabled INTEGER);
CREATE TABLE evo_member_attendance(unit TEXT,evo_member_id TEXT,attendance_date TEXT,activity_name TEXT);
CREATE TABLE audit_log(actor_type TEXT,actor_id TEXT,action TEXT,metadata_json TEXT,created_at TEXT);
CREATE TABLE evo_member_contracts(unit TEXT,evo_member_id TEXT,id_membership TEXT,start_date TEXT,end_date TEXT,cancel_date TEXT,membership_status TEXT);
CREATE TABLE members(id INTEGER PRIMARY KEY,evo_member_id INTEGER,gym_client_id TEXT,status TEXT);
CREATE TABLE auth_sessions(token_hash TEXT,member_id INTEGER,revoked_at TEXT,expires_at TEXT);
CREATE TABLE app_content(content_key TEXT PRIMARY KEY,content_json TEXT,updated_at TEXT);
INSERT INTO club_voucher_models VALUES(1,'bike','Teste 20%',1,20,15,'[123]',1);
INSERT INTO evo_unit_config VALUES('bike','test','test-token','2099-01-01',1);
INSERT INTO members VALUES(1,99,NULL,'ACTIVE');
INSERT INTO evo_member_attendance VALUES('bike','99','2026-10-01','Bike'),('bike','99','2026-10-02','Bike');
`);
const wrap=(sql,args=[])=>({bind(...a){return wrap(sql,a)},async first(){return db.prepare(sql).get(...args)||null},async all(){return {results:db.prepare(sql).all(...args)}},async run(){const r=db.prepare(sql).run(...args);return {meta:{changes:r.changes,last_row_id:Number(r.lastInsertRowid)}}},sql,args});
const env={DB:{prepare:sql=>wrap(sql),async batch(items){db.exec('BEGIN');try{const r=items.map(x=>{const y=db.prepare(x.sql).run(...x.args);return {meta:{changes:y.changes,last_row_id:Number(y.lastInsertRowid)}}});db.exec('COMMIT');return r}catch(e){db.exec('ROLLBACK');throw e}}}};
const member={id:1,evo_member_id:99,gym_client_id:null},mission={id:'test-mission',unit:'bike',type:'challenge',status:'Ativo',start:'2026-10-01',end:'2099-01-01',tasks:[{type:'presence',quantity:2,distinctDays:true}],goals:[]},goal={id:'goal-1',value:1,rewards:[{type:'voucher',rewardId:'bike:1'}]};mission.goals=[goal];
db.prepare('INSERT INTO app_content VALUES(?,?,NULL)').run('club-pop',JSON.stringify({missionList:[mission]}));
const token='fixture-token';db.prepare('INSERT INTO auth_sessions VALUES(?,?,NULL,?)').run(crypto.createHash('sha256').update(token).digest('hex'),1,'2099-01-01');
return {db,env,member,mission,goal,claim:()=>claimEvoMissionVoucher(env,member,mission,goal,goal.rewards),token};}
async function run(fn,mock){const old=globalThis.fetch;globalThis.fetch=mock;try{await fn()}finally{globalThis.fetch=old}}
const success=(url,opt)=>{assert(url.startsWith('https://evo-integracao-api.w12app.com.br/api/'));if(opt.method==='POST'){const b=JSON.parse(opt.body);assert.equal(b.qtde,1);assert.equal(b.flIlimitado,false);assert.equal(b.valor,20);assert.deepEqual(b.idsContratos,[123]);return Response.json({voucherId:456})}assert(url.includes('/get-codes-by-voucher-id/456?take=1&skip=0'));return Response.json({quantity:1,list:[{voucherId:456,voucherCode:'REAL-EVO-CODE'}]})};
test('successful claim: real code, D1, accounting, repeat click without EVO',async()=>{const f=fixture();let calls=0;await run(async()=>{const a=await f.claim();assert.equal(a.voucher,'REAL-EVO-CODE');assert.equal(a.evoRequestsMade,2);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM evo_request_log').get().n,2);const b=await f.claim();assert(b.alreadyClaimed);assert.equal(b.evoRequestsMade,0);assert.equal(calls,2);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM vouchers').get().n,1);assert.equal(f.db.prepare('SELECT status FROM club_voucher_requests').get().status,'issued');f.db.close()},async(...a)=>{calls++;return success(...a)})});
test('concurrent clicks cannot create two EVO vouchers',async()=>{const f=fixture();let posts=0;await run(async()=>{await Promise.all([f.claim(),f.claim()]);assert.equal(posts,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM vouchers').get().n,1);f.db.close()},async(...a)=>{if(a[1].method==='POST')posts++;return success(...a)})});
test('POST timeout never reissued; no local code fabricated',async()=>{const f=fixture();let calls=0;await run(async()=>{const a=await f.claim(),b=await f.claim();assert(a.requiresReview&&b.requiresReview);assert.equal(calls,1);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM vouchers').get().n,0);assert.equal(f.db.prepare('SELECT ok FROM evo_request_log').get().ok,0);f.db.close()},async()=>{calls++;throw Error('simulated timeout')})});
test('code query fails then resumes by ID; POST not repeated',async()=>{const f=fixture();let posts=0,gets=0;await run(async()=>{const a=await f.claim();assert(a.canRetryCode);assert.equal(f.db.prepare('SELECT evo_voucher_id FROM club_voucher_requests').get().evo_voucher_id,456);const b=await f.claim();assert.equal(b.voucher,'REAL-EVO-CODE');assert.equal(posts,1);assert.equal(gets,2);f.db.close()},async(...a)=>{if(a[1].method==='POST')posts++;else if(++gets===1)return new Response('unavailable',{status:503});return success(...a)})});
test('rejects wrong/empty response, never uses numeric ID as code',()=>{for(const data of [{voucherId:456},{quantity:1,list:[]},{quantity:1,list:[{voucherId:789,voucherCode:'WRONG'}]},{quantity:1,list:[{voucherId:456,voucherCode:''}]}])assert.equal(evoVoucherCode(data,456),null)});
test('eligibility/config/model failures: zero EVO; unrelated unit protected',async()=>{await run(async()=>{
for(const change of [f=>f.goal.rewards[0].rewardId='gym:1',f=>f.mission.status='Inativo',f=>f.mission.tasks[0].quantity=3,f=>f.db.exec('UPDATE club_voucher_models SET enabled=0'),f=>f.db.exec('UPDATE evo_unit_config SET enabled=0'),f=>{f.mission.eligibility='selected';f.mission.contracts=['bike:123']},f=>f.goal.rewards.push({type:'fitcoins',amount:100})]){const f=fixture();change(f);await assert.rejects(f.claim());assert.equal(f.db.prepare('SELECT COUNT(*) n FROM vouchers').get().n,0);f.db.close()}
},async()=>{throw Error('EVO must not be called')})});
test('HTTP route authenticates; listing is D1 only; claim routes voucher array instead of manual code',async()=>{const f=fixture();await run(async()=>{const req=(path,body,auth=true)=>new Request('https://worker'+path,{method:body?'POST':'GET',headers:{...(auth?{Authorization:'Bearer '+f.token}:{}),'content-type':'application/json'},...(body?{body:JSON.stringify(body)}:{})});
const body={missionId:f.mission.id,goalId:f.goal.id};assert.equal((await worker.fetch(req('/mission-redemptions/claim',body,false),f.env)).status,401);
const response=await worker.fetch(req('/mission-redemptions/claim',body),f.env);assert.equal(response.status,200);assert.equal((await response.json()).voucher,'REAL-EVO-CODE');
globalThis.fetch=async()=>{throw Error('Listing must be D1 only')};const listing=await worker.fetch(req('/student-vouchers'),f.env);assert.equal(listing.status,200);const d=await listing.json();assert.equal(d.vouchers[0].code,'REAL-EVO-CODE');assert.equal(d.pending.length,0);f.db.close();},async(...a)=>success(...a))});
test('proxy does not invoke Fitcoins for EVO voucher or pending emission',async()=>{let s=fs.readFileSync(new URL('./api/mission-redemptions.js',import.meta.url),'utf8');s=s.replace(/^import .*?;\n/,'const executeFitcoinReward=()=>{throw Error("FITCOINS_MUST_NOT_RUN")};\n');const {default:proxy}=await import('data:text/javascript;base64,'+Buffer.from(s).toString('base64'));await run(async()=>{for(const d of [{ok:true,rewardType:'voucher',voucher:'REAL-EVO-CODE'},{ok:true,rewardType:'voucher',requiresReview:true}]){globalThis.fetch=async()=>Response.json(d);const res={status(n){this.code=n;return this},setHeader(){return this},json(x){this.body=x;return this}};await proxy({query:{route:'claim'},method:'POST',headers:{authorization:'Bearer fixture'},body:{}},res);assert.equal(res.code,200);assert.deepEqual(res.body,d)}},async()=>{})});
test('voucher UI script compiles and distinguishes EVO from internal codes',()=>{const s=fs.readFileSync(new URL('./meus-vouchers.html',import.meta.url),'utf8');for(const m of s.matchAll(/<script\b[^>]*>([\s\S]*?)<\/script>/g))new vm.Script(m[1]);assert(s.includes('RECUPERAR CÓDIGO EVO'));assert(s.includes('Código emitido pela EVO'));assert(!s.includes('Volte amanhã'))});
