const OWNER="rvilelas1984",REPO="loja-pop",PATH="data/club-pop.json",BRANCH="main";
const parse=async r=>{const t=await r.text();try{return JSON.parse(t)}catch{return {raw:t.slice(0,300)}}};
const authHeader=(dns,token)=>({Authorization:"Basic "+Buffer.from(dns+":"+token).toString("base64"),Accept:"application/json"});
const fitValue=d=>{const x=Array.isArray(d)?d[0]:d,v=x?.totalFitCoins??x?.totalFitcoins;return Number.isFinite(Number(v))?Number(v):null};
const wait=ms=>new Promise(r=>setTimeout(r,ms));
async function verifiedBalance(url,headers,expected){let last=null;for(let i=0;i<4;i++){if(i)await wait(650*i);const r=await fetch(url,{headers,cache:"no-store"}),d=await parse(r),v=fitValue(d);if(r.ok&&v!=null){last=v;if(expected==null||v===expected)return {ok:true,balance:v}}}return {ok:false,balance:last}}
async function gh(path,opt={}){const h={"accept":"application/vnd.github+json","user-agent":"club-pop",...(opt.headers||{})};if(process.env.GITHUB_TOKEN)h.authorization="Bearer "+process.env.GITHUB_TOKEN;return fetch("https://api.github.com"+path,{...opt,headers:h})}
async function content(){const r=await gh("/repos/"+OWNER+"/"+REPO+"/contents/"+PATH+"?ref="+BRANCH);if(!r.ok)throw Error("Não foi possível carregar o catálogo");const j=await r.json();return {data:JSON.parse(Buffer.from(j.content,"base64").toString("utf8")),sha:j.sha}}
async function save(data,sha){const payload={message:"Registra resgate Club Pop",content:Buffer.from(JSON.stringify(data,null,2)).toString("base64"),sha,branch:BRANCH};const r=await gh("/repos/"+OWNER+"/"+REPO+"/contents/"+PATH,{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});if(!r.ok)throw Error("Falha ao registrar resgate")}
export default async function handler(req,res){if(req.method!=="POST")return res.status(405).json({ok:false,error:"Método não permitido"});const bearer=req.headers.authorization;if(!bearer)return res.status(401).json({ok:false,error:"Sessão do aluno ausente"});try{
 const meR=await fetch("https://club-pop-api.renato-vilelas-personal.workers.dev/auth/me",{headers:{Authorization:bearer,Accept:"application/json"}}),me=await parse(meR);if(!meR.ok||!me?.ok)return res.status(401).json({ok:false,error:"Sessão inválida"});
 const idMember=me.member?.evoMemberId||me.member?.evo_member_id;if(!idMember)return res.status(400).json({ok:false,error:"Cadastro Bike Pop não vinculado"});
 const sourceType=String(req.body?.sourceType||"product"),sourceId=String(req.body?.sourceId||"");if(!["product","service"].includes(sourceType)||!sourceId)return res.status(400).json({ok:false,error:"Item inválido"});
 const {data,sha}=await content();data.redemptions??=[];data.transactions??=[];const list=sourceType==="service"?(data.services||[]):(data.products||[]),item=list.find(x=>String(x.id)===sourceId&&x.status==="Ativo");if(!item)return res.status(404).json({ok:false,error:"Item não encontrado ou inativo"});
 const cost=Math.max(0,Number(item.fitcoins||0));if(cost<1)return res.status(400).json({ok:false,error:"Este item não possui valor em Fitcoins"});
 const dns=process.env.EVO_DNS,token=process.env.EVO_TOKEN;if(!dns||!token)return res.status(503).json({ok:false,error:"Credenciais EVO Bike Pop não configuradas"});
 const headers=authHeader(dns,token),fitUrl="https://evo-integracao-api.w12app.com.br/api/v1/members/"+encodeURIComponent(idMember);
 const beforeR=await fetch(fitUrl,{headers,cache:"no-store"}),beforeD=await parse(beforeR),before=fitValue(beforeD);if(!beforeR.ok||before==null)return res.status(502).json({ok:false,error:"Não foi possível confirmar o saldo de Fitcoins",detail:beforeD?.message||beforeD?.error||beforeD?.raw||"",stage:"balance-before"});if(before<cost)return res.status(409).json({ok:false,error:"Saldo de Fitcoins insuficiente",balance:before,cost});
 const key=String(req.body?.idempotencyKey||"").replace(/[^a-zA-Z0-9_-]/g,"").slice(0,80);if(key){const prior=data.redemptions.find(x=>x.idempotencyKey===key);if(prior)return res.status(200).json({ok:true,duplicate:true,redemption:prior,balance:prior.balanceAfter})}
 const qs=new URLSearchParams({idMember:String(idMember),type:"2",fitcoin:String(cost),reason:"Club Pop - Resgate - "+String(item.name||"Item").slice(0,80)}),debitR=await fetch("https://evo-integracao-api.w12app.com.br/api/v1/members/fitcoins?"+qs,{method:"PUT",headers}),debitD=await parse(debitR);if(!debitR.ok)return res.status(debitR.status).json({ok:false,error:"EVO não autorizou o débito de Fitcoins",detail:debitD?.message||debitD?.error||debitD?.result||debitD?.raw||("HTTP "+debitR.status),stage:"evo-debit"});
 const check=await verifiedBalance(fitUrl,headers,before-cost),after=check.balance;if(!check.ok)return res.status(502).json({ok:false,error:"Débito enviado à EVO, mas o saldo atualizado ainda não pôde ser confirmado. Não tente novamente; procure a recepção.",balanceBefore:before,balanceAfter:after,expected:before-cost,stage:"balance-after"}); const receipt="CP-"+Date.now().toString(36).toUpperCase(),redemption={id:"redeem-"+Date.now(),idempotencyKey:key||receipt,receipt,sourceType,sourceId,title:item.name,memberId:String(idMember),memberName:[me.member?.first_name||me.member?.firstName,me.member?.last_name||me.member?.lastName].filter(Boolean).join(" "),unit:"bike",fitcoins:cost,balanceBefore:before,balanceAfter:after,paymentMethod:"FITCOINS",status:sourceType==="service"?"AGUARDANDO_UTILIZACAO":"AGUARDANDO_ENTREGA",createdAt:new Date().toISOString(),evoResult:debitD};data.redemptions.push(redemption);data.transactions.push({id:"tx-"+Date.now(),reference:receipt,memberId:String(idMember),memberName:redemption.memberName,origin:"store",description:item.name,paymentMethod:"FITCOINS",direction:"debit",fitcoins:cost,balanceBefore:before,balanceAfter:after,status:"COMPLETED",redemptionId:redemption.id,createdAt:redemption.createdAt});await save(data,sha);return res.status(200).json({ok:true,redemption,balance:after});
 }catch(e){return res.status(500).json({ok:false,error:"Não foi possível concluir o resgate",detail:String(e.message||e).slice(0,220)})}}